package com.wixpress.app.dao;

import org.codehaus.jackson.JsonNode;

/**
 * Data store wrapper
 * It implements methods for getting and setting data in the data store
 */
public interface AppDao {


    /**
     * Get app settings from the data store
     * @param userId  - The Wix user id of the app.
     * @return the app settings of this user
     */
    public AppSettings getAppSettings(String userId);

    /**
     * Save app settings in the data store
     * @param userId  - The Wix user id of the app.
     * @param appSettings - The settings of the app that configure the widget
     * @return true if the settings were successfully saved to the DB
     */
    public Boolean saveAppSettings(String userId, AppSettings appSettings);

    /**
     * Get app project from the data store (For widget displaying)
     * @param instanceId - Instance id of the app, It is shared by multiple Widgets of the same app within the same site
     * @param compId     - The ID of the Wix component which is the host of the iFrame, it is used to distinguish between multiple instances of the same Widget in a site
     * @return the app project of this user
     */
    public JsonNode getAppProjectCode(String instanceId, String compId);

    /**
     * Get app project from the data store (For widget displaying)
     * @param userId - - The Wix user id of the app.
     * @param projectId     - - The projectId (UUID generated by the editor)
     * @return the app project of this user
     */
    public AppProject getAppProject(String userId, String projectId);

    /**
     * Save app settings in the data store
     * @param userId  - The Wix user id of the apgp.
     * @param projectId  - The Wix user id of the app.
     * @param appProject - The project to save
     * @return true if the project was successfully saved to the DB
     */
    public Boolean saveAppProject(String userId, String projectId, AppProject appProject);

    /**
     * Save app settings in the data store
     * @param userId  - The Wix user id of the apgp.
     * @param projectIds  - The projects ids to save
     * @param appProjects - The projects data to save
     * @return true if the project was successfully saved to the DB
     */
    public Boolean saveAppProjects(String userId, String[] projectIds, AppProject[] appProjects);


    /**
     * Save a correlation between a given app instance and a projectId
     *
     * @param userId - The Wix user id of the app.
     * @param instanceId - Instance id of the app, It is shared by multiple Widgets of the same app within the same site
     * @param compId     - The ID of the Wix component which is the host of the iFrame, it is used to distinguish between multiple instances of the same Widget in a site
     * @param projectId  - The projectId (UUID generated by the editor)
     * @return true if the publish was successful
     */
    public Boolean publishProject(String userId, String instanceId, String compId, String projectId);


    //public List<AppProject> getRevisions(String userId);
    //public Boolean restoreToRevisionNumber(String userId, int revisionNumber);
}
